### PR TITLE
feat(cxl-ui): jobs basic layout, using cxl-app-layout

### PR DESCRIPTION
**Pull request by freudFlintstone**
Added `cxl-app-layout`, which is compatible with cxl-institute-layout, via `[theme="cxl-institute-layout"`.
`cxl-app-layout` defaults to a one column layout, ignoring the aside element.

### CODE REVIEW

**Comment by lkraav** [comment]
Hi @freudFlintstone mind rebasing this on latest `master`?

**Comment by lkraav** [comment]
It's also clear cxl-app-layout needs to be a separate PR. This is too big.

**Comment by freudFlintstone** [comment]
OK, sure I'll separate it.

**Comment by lkraav** [comment]
Jobs site requirements got simplified and implemented on existing components.

**Pull request closed without merging**
