### PR TITLE
feat(cxl-ui): light-card layout updates

### PR DESCRIPTION
**Pull request by HenerHoop**
https://app.clickup.com/t/86ayhhg16

### CODE REVIEW

**Comment by HenerHoop** [comment]
@pawelkmpt After @freudFlintstone comments under the second PR, I did it the way it was originally intended. There was some miscommunication. The second PR can be deleted once it's accepted.

**Review by freudFlintstone — CHANGES_REQUESTED** [review]
The only issue I found is that the instructor name is aligned to the bottom in the designs. Other than that, great turn around on this one, I agree the other PR should be canceled.
image

**Review by pawelkmpt — CHANGES_REQUESTED** [review]
@HenerHoop cards itself are looking good. I just found few inconsistencies comparing to the design

**1. Portrait card** 

Prevent image corner to leak out the box

Screenshot 2023-10-31 at 09 59 04

---

**2. Three lines title**

Design shows 3 lines in the title.
Screenshot 2023-10-31 at 10 04 35

Our card displays just 2.
Screenshot 2023-10-31 at 10 03 27

---

**3. Card in progress** 

Design hides instructor name on "in progress" card.

Screenshot 2023-10-31 at 10 04 35

Our card still shows it.

---

**4. Extreme lengths** 

Design and comment suggest card to grow for extreme cases

Screenshot 2023-10-31 at 10 14 17

Our looks like this:

Screenshot 2023-10-31 at 10 06 40

**Review by pawelkmpt — CHANGES_REQUESTED** [review]
Commit message

```diff
- feat(cxl-ui): light-card layout updates
+ feat(cxl-ui): cxl-light-card add portrait mode, progress bar
```

**Comment by pawelkmpt** [comment]
Task linked: [CU-86ayhhg16 Lite card component layouts](https://app.clickup.com/t/86ayhhg16)

**Review by pawelkmpt — APPROVED** [review]

**Pull request merged**
