### PR TITLE
QA Playbook Viewer

### PR DESCRIPTION
**Pull request by dominik-stypula-polcode**
Issue reference: https://github.com/conversionxl/cxl-playbook-blocks/issues/94
Video: https://www.loom.com/share/e507af8d115d4e8a8472660cbfc25305

### CODE REVIEW

**Comment by dominik-stypula-polcode** [comment]
Hi @lkraav I've got notice this is important to introduce to the staging WP ASAP, is there anything for me to fix in this PR?

**Comment by heshfekry** [comment]
@lkraav 

This PR should fix a few UI issues from previous QA/iteration work.

**Comment by pawelkmpt** [comment]
What's the status of it @dominik-stypula-polcode @lkraav @heshfekry ?

**Comment by heshfekry** [comment]
@pawelkmpt  This should be closed as it has been broken up into smaller issues.

For example:
https://app.clickup.com/t/pb8hbb
https://app.clickup.com/t/mfc2j3
and others.

**Comment by heshfekry** [comment]
@pawelkmpt  This should be closed as it has been broken up into smaller issues.

For example:
https://app.clickup.com/t/pb8hbb
https://app.clickup.com/t/mfc2j3
and others.

**Pull request closed without merging**
