### PR TITLE
refactor(cxl-ui): implement dashboard facelift

### PR DESCRIPTION
**Pull request by freudFlintstone**
https://app.clickup.com/t/86ayt69ga

dependencies: #365

### CODE REVIEW

**Comment by freudFlintstone** [comment]
Task linked: [CU-86ayt69ga Dashboard facelift](https://app.clickup.com/t/86ayt69ga)

**Review by pawelkmpt — CHANGES_REQUESTED** [review]
@freudFlintstone mobile is broken...

Also please rebase on top of `master`

Screenshot 2023-12-18 at 12 14 22
Screenshot 2023-12-18 at 12 14 32
Screenshot 2023-12-18 at 12 14 47

**Comment by heshfekry** [comment]
@freudFlintstone put it back to original width not half-width then. removes the problem?

**Comment by pawelkmpt** [comment]
Please also make stat font consistent

Screenshot 2023-12-18 at 13 17 47

**Comment by freudFlintstone** [comment]
> And one more thing in featured slider, image corner is visible "above" rounded corner. It should be hidden "behind".
> 
> https://www.loom.com/share/dce82d61ade041569094ef01d3a113fa?sid=7e8d288a-800a-450a-9155-32071e1f7bb1

@pawel I had seen that already. The problem is how the browser renders those transitions. I don't have a solution yet.
The obvious fix (giving the same border with overflow: hidden to the outermost parent, doesn't work). I'm going to do some research on this.

**Review by pawelkmpt — CHANGES_REQUESTED** [review]
Right  padding needed for blue sections

Screenshot 2023-12-18 at 16 26 27
Screenshot 2023-12-18 at 16 26 46

**Review by pawelkmpt — APPROVED** [review]

**Pull request merged**
