### PR TITLE
feat(cxl-ui): primary menu tweaks, make sticky, disable page scrolling, few fixes etc.

### PR DESCRIPTION
**Pull request by saas786**
Dep: https://github.com/conversionxl/wp-theme-lib/pull/66
cu-task parent task: https://app.clickup.com/t/2z64umf

### CODE REVIEW

**Review by anoblet — COMMENTED** [review]
This is an edge case, though if I user were to open a menu, then scroll, the menu loses it's position. Should we be closing the menu if the user scrolls?

deploy-preview-230--conversionxl-aybolit netlify app__path=_story_cxl-ui-cxl-app-layout--cxl-app-layout-1-cw (1)

**Comment by saas786** [comment]
> This is an edge case, though if a user were to open a menu, then scroll, the menu loses it's position. Should we be closing the menu if the user scrolls?
> 
> deploy-preview-230--conversionxl-aybolit netlify app__path=_story_cxl-ui-cxl-app-layout--cxl-app-layout-1-cw (1)

Mostly yes, it should close it, and simpler solution.

If we don't close it, we will have to trigger cxl-marketing-nav update of some sort, so it re-calculate the opened dropdown.

**Review by pawelkmpt — CHANGES_REQUESTED** [review]
Guys, be consistent. One uses "primary menu", other "[cxl-marketing-nav]" and everything is about the same component.

In git log I see different approaches but the simplest seems to be just using `cxl-marketing-nav`. Apply to every commit and additionally:

0f05fc753a92d347a8bc2e4a430a2a909cf5daaf
```diff
- feat(cxl-ui): primary menu should be sticky when scrolling
+ feat(cxl-ui): cxl-marketing-nav make sticky on scroll
```
---

Do we need so many commits? Can we squash some?

**Comment by saas786** [comment]
> Do we need so many commits? Can we squash some?

@pawelkmpt 

Yes, each commit does separate logic, I intentionally organized them into separate commits.

**Review by pawelkmpt — APPROVED** [review]

**Comment by pawelkmpt** [comment]
@saas786 do you want to send more changes or can merge?

**Comment by saas786** [comment]
> @saas786 do you want to send more changes or can merge?

If its working on your end, no more changes from my end.

**Comment by lkraav** [comment]
Not liking what I'm seeing here for 80+% of this code, starting with randomly invented body classes.

Unfortunately no bandwidth to dig into it for a few weeks at least, but components will lose any coherency if more stuff like this gets in.

**Comment by saas786** [comment]
> Not liking what I'm seeing here for 80+% of this code, starting with randomly invented body classes.
> 
> Unfortunately no bandwidth to dig into it for a few weeks at least, but components will lose any coherency if more stuff like this gets in.

When you get a chance, please provide feedback.

**Pull request merged**
