### PR TITLE
fix(cxl-lumo-styles): limit secondary font style in ul to .entry-content

### PR DESCRIPTION
**Pull request by freudFlintstone**
As requested in [cxl-wpstarter PR](https://github.com/conversionxl/cxl-wpstarter/pull/283#pullrequestreview-1757302024)

Tested locally:

Screenshot from 2023-11-30 11-19-55
Screenshot from 2023-11-30 11-20-29

### CODE REVIEW

**Comment by lkraav** [comment]
Yeah, in theory it will improve current state.

But we just discussed things with @heshfekry and maybe be opting for a deep simplification by "reset all to single typeface, expand from there".

Let's see what the decision will be there, this PR might then need to morph into just removing usage (but not definition) of secondary typeface.

**Comment by pawelkmpt** [comment]
Task linked: [CU-86aytq9gd Fix paragraph vs element fonts](https://app.clickup.com/t/86aytq9gd)

**Comment by lkraav** [comment]
> what about global p style

Yep, highly likely also needs to be contained with `.entry-content`, but we discussed the big elephant in the room in a @heshfekry huddle today
* in WP almost everything is a content page
* thus has `.entry-content` element
* we might need some sort of a content categorization system, if we are to continue with multiple typefaces
* ...or we try "big single-typeface sans-serif-only reset", and start over from there looking into where and how "secondary" or "serif" can be implemented for various glorious benefits

**Comment by pawelkmpt** [comment]
> > what about global p style
> 
> Yep, highly likely also needs to be contained with `.entry-content`, but we discussed the big elephant in the room in a @heshfekry huddle today

It is already. First line could be dropped @freudFlintstone.
```
 {
  font-family: var(--cxl-lumo-font-secondary);
  .entry-content & {
    font-family: var(--cxl-lumo-font-secondary);
  }
```


> * in WP almost everything is a content page
> * thus has `.entry-content` element

Yeah, it's tricky.

> * we might need some sort of a ~content~ page categorization system, if we are to continue with multiple typefaces: for example, out of post type `page`, only sales pages should probably have serif content.
> * ...or we try "big single-typeface sans-serif-only reset", and start over from there looking into where and how "secondary" or "serif" can be implemented for various glorious benefits

Will be next step. For now let's just focus on patching recent changes.

**Comment by freudFlintstone** [comment]
> > > what about global p style
> > 
> > 
> > Yep, highly likely also needs to be contained with `.entry-content`, but we discussed the big elephant in the room in a @heshfekry huddle today
> 
> It is already. First line could be dropped @freudFlintstone.
> 
> ```
>  {
>   font-family: var(--cxl-lumo-font-secondary);
>   .entry-content & {
>     font-family: var(--cxl-lumo-font-secondary);
>   }
> ```
> 
> > * in WP almost everything is a content page
> > * thus has `.entry-content` element
> 
> Yeah, it's tricky.
> 
> > * we might need some sort of a ~content~ page categorization system, if we are to continue with multiple typefaces: for example, out of post type `page`, only sales pages should probably have serif content.
> > * ...or we try "big single-typeface sans-serif-only reset", and start over from there looking into where and how "secondary" or "serif" can be implemented for various glorious benefits
> 
> Will be next step. For now let's just focus on patching recent changes.

If we drop the first line, we'll  have mixed typefaces in entry-content, like the courses. <ul> will use sans-serif while the rest of the paragraphs use the serif font.

**Comment by freudFlintstone** [comment]
@pawelkmpt how are you getting that? I only see the new one:
image

If that's from your IDE? If that's a merge, there's a problem with it

**Comment by pawelkmpt** [comment]
> If that's from your IDE? If that's a merge, there's a problem with it

I linked to the piece of code in

> @lkraav what about global p style? [It was also set](https://github.com/conversionxl/aybolit/commit/a22bd56f5d642874fce23a6c984adda61730ced7#diff-d1203ee8254710ebcb534808aedfcd99ea85d5ce8d304e7ea2b8bdd5782e24f8R146) to secondary font family and one of the pieces affected is course about section:

**Review by pawelkmpt — APPROVED** [review]

**Pull request merged**
