### PR TITLE
fix: set vaadin-tab.current-menu-item[selected] for active tab

### PR DESCRIPTION
**Pull request by freudFlintstone**

### CODE REVIEW

**Comment by lkraav** [comment]
This looks like it's going in the right direction.

Is it possible to also add a demonstration in Storybook for it? Add .current-menu-item to some tab. Unless one has it already, I forget.

**Comment by freudFlintstone** [comment]
I tried that it didn't work in the storybook, but the logic certainly works in production, as I tested it in the console. 

I'm investigating further, will let you know

**Comment by freudFlintstone** [comment]
OK, the issue is that vaadin-tabs is not populated by the time firstUpdated runs. So this needs to be done somewhere else.

**Comment by lkraav** [comment]
Ah right. This means we should do the selection choice after context menu item population logic, not firstUpdated.

**Comment by freudFlintstone** [comment]
Seems like this is the best spot. Although the `changedProps.has('contextMenuItems')`condition in is not meant for us to deal with menu state and I don't consider good practice mixing those, this issue is actually dependent on that prop update.

**Comment by lkraav** [comment]
> OK, the issue is that vaadin-tabs is not populated by the time firstUpdated runs. So this needs to be done somewhere else.

`firstUpdated()` actually does work, as it should - DOM is fully populated by the time it executes.

That being said, I did notice some inconsistent off/on behavior when reloading Storybook, almost looking like a race condition of some sort.

But on real staging app site everything seemed to work fine when navigating pages, therefore I'm giving 6f6b3dd80e7a4b4b58f3c9ef6ed9e563a0bb23c1 a shot until proven otherwise live, and we can move on to the next thing.

**Pull request closed without merging**
