### PR TITLE
feat: marketing layout as separate cxl-marketing-layout component

### PR DESCRIPTION
**Pull request by chanar**
- removed cxl-marketing-layout package
- added cxl-marketing-layout component and storybook demo

### CODE REVIEW

**Comment by chanar** [comment]
I might need to publish new version of packages as well if you want to run it.

yarn
yarn build-styling
yarn storybook

**Comment by lkraav** [comment]
This is too hard to review as-is. When I wrote "clean branch" in #2, it means "avoid randomness like banner card" stuff. One thing at a time, at all times, or reviews will simply not happen. I'm squashing it all into a single commit locally and then dig into understanding this structure proposal.

**Comment by lkraav** [comment]
```
aybolit-conversionxl-2-marketing-layout $ [git:2-marketing-layout?{1}] yarn
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@conversionxl/cxl-marketing-layout/-/cxl-marketing-layout-0.1.1.tgz: Request failed \"404 Not Found\"".                                                                    
info If you think this is a bug, please open a bug report with the information provided in "/home/leho/Documents/web-components/aybolit-conversionxl-2-marketing-layout/yarn-error.log".                                                     
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

https://github.com/conversionxl/aybolit/blob/58982f47bb0b0ad057ddf23393cc27fc3b82d141/yarn.lock#L715

Without `yarn.lock`:

```
aybolit-conversionxl-2-marketing-layout $ [git:2-marketing-layout+?{1}] yarn
yarn install v1.15.2
info No lockfile found.
[1/4] Resolving packages...
warning @storybook/addon-knobs > @storybook/components > recompose > fbjs > core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning vrtest > fs-promise@1.0.0: Use mz or fs-extra^3.0 with Promise Support
warning vrtest > image-diff > buffered-spawn > cross-spawn-async@1.0.1: cross-spawn no longer requires a build toolchain, use it instead
error Couldn't find package "@conversionxl/cxl-marketing-layout@^0.1.0" required by "@aybolit/storybook@0.1.0" on the "npm" registry.
```

**Comment by chanar** [comment]
@lkraav try now.

**Comment by lkraav** [comment]
Thanks, it builds now and I can continue working on the structure.

In the meanwhile, it would be helpful if you rebased both feature branches on top of today's `conversionxl/aybolit:master` or I need to repeat it every time you update something.

You could also continue by amending and force-pushing over https://github.com/conversionxl/aybolit/tree/leho-2-marketing-layout if rebase practice is out of reach right now.

**Comment by lkraav** [comment]
Struggling to understand the purpose of these, what look like to be copy-pasta files:

https://github.com/conversionxl/aybolit/blob/2-marketing-layout/packages/cxl-theme/scss/lumo-colors.scss
https://github.com/conversionxl/aybolit/blob/2-marketing-layout/packages/cxl-theme/scss/lumo-typography.scss

It isn't clear if these contain just overrides and/or do we really have that many (files look too big to be only overrides?), or just legacy copy-pasta to get something done in the past, and hasn't been cleaned up.

**Comment by lkraav** [comment]
https://github.com/conversionxl/aybolit/blob/2-marketing-layout/packages/cxl-theme/scss/vaadin-button.scss#L25

All `theme` attribute names are custom inventions, or some, or...? There seems to be zero system to it. For one, it might make sense to prefix/namespace everything with `cxl-` so we can tell the difference.

**Comment by lkraav** [comment]
https://github.com/conversionxl/aybolit/blob/2-marketing-layout/packages/cxl-theme/scss/_inject.scss

I haven't seen any framework lately to use "inject" terminology for something. Isn't this a mixing of some sort? What's the difference between "inject" and "mixin" in your mind?

**Comment by chanar** [comment]
> It isn't clear if these contain just overrides and/or do we really have that many (files look too big to be only overrides?), or just legacy copy-pasta to get something done in the past, and hasn't been cleaned up.

Yes, correct. It's copy paste. Just commented on similar question here https://github.com/conversionxl/aybolit/issues/5#issuecomment-483564275

**Comment by chanar** [comment]
> https://github.com/conversionxl/aybolit/blob/2-marketing-layout/packages/cxl-theme/scss/vaadin-button.scss#L25
> 
> All `theme` attribute names are custom inventions, or some, or...? There seems to be zero system to it. For one, it might make sense to prefix/namespace everything with `cxl-` so we can tell the difference.

I have kept the vaadin component naming. For example, /templates/vaadin-dialog-overlay.js extends vaadin-dialog-overlay component styles. Also, vaadin uses theme-for="" attribute with the same naming. So, I saw it as closest possible option. 

https://github.com/conversionxl/aybolit/blob/165c637c3d6b254776677a255e62c7998e396c39/packages/cxl-theme/src/templates/vaadin-dialog-overlay.js#L6

**Comment by chanar** [comment]
> https://github.com/conversionxl/aybolit/blob/2-marketing-layout/packages/cxl-theme/scss/_inject.scss
> 
> I haven't seen any framework lately to use "inject" terminology for something. Isn't this a mixin of some sort? What's the difference between "inject" and "mixin" in your mind?
> 
> What about `@extend` https://sass-lang.com/guide#topic-7

Yeah, cannot argue with this. But what's in inject is different from mixins and extends. Inject contains CSS that should be injected in every component. Before we used webpack loader "sass-resources-loader" that automatically placed the scss in the beginning of every css.

https://github.com/conversionxl/cxl-app/blob/521586bcbfa14d436c246698375fd552de522ec3/utils/webpack.common.js#L24

For example inject contains .text-primary that is a short hand class to make some text CXL red. Also .flex etc. I think this inject could be called theme.scss.

**Comment by lkraav** [comment]
> > All theme attribute names are custom inventions, or some, or...?
> Also, vaadin uses theme-for="" attribute with the same naming. So, I saw it as closest possible option.

Ah, I realized I missed being clear about "attribute values" being the issue, rather than attribute name. I'm aware of `theme-for` attribute name, but the random words attribute value system is :thinking:.

Prefixing `cxl-` for values does seem like a thing, since upstream seems to be doing the same.

**Comment by chanar** [comment]
Hmm, we could do it so that `/templates/vaadin-ordered-layout.js` becomes `cxl-vaadin-ordered-layout.js`? And dom module would look like

`<dom-module id="cxl-lumo-horizontal-layout" theme-for="vaadin-horizontal-layout">`

instead of 

`<dom-module id="lumo-horizontal-layout-edit" theme-for="vaadin-horizontal-layout">`

(note that we cannot change theme-for naming)

Maybe ordered-layout is not so good example because usually theme-for has the exact name of the vaadin component eg. "vaadin-button"

**Pull request closed without merging**
