### PR TITLE
Add comment icon

### PR DESCRIPTION
**Pull request by pawelkmpt**
Needed here:
* #122 
* #123
* https://github.com/conversionxl/cxl-playbook-blocks/pull/142

### CODE REVIEW

**Comment by lkraav** [comment]
There should always be something in the PR using it, or purpose unclear.

**Comment by pawelkmpt** [comment]
updated

**Comment by lkraav** [comment]
> updated

I mean this icon should be a part of a bigger PR not a standalone thing.

**Comment by pawelkmpt** [comment]
I don't have bigger things

**Comment by lkraav** [comment]
> I don't have bigger things

This should be demo'd in a story https://github.com/conversionxl/aybolit/blob/playbooks/packages/storybook/cxl-ui/cxl-vaadin-accordion/cxl-playbook-accordion.story.js

**Comment by lkraav** [comment]
Superceded by #126

**Pull request closed without merging**
