### PR TITLE
fix(cxl-ui): [cxl-marketing-nav] display descriptions on sub-menus

### PR DESCRIPTION
**Pull request by anoblet**
https://app.clickup.com/t/861m7gmrz

### CODE REVIEW

**Review by lkraav — COMMENTED** [review]
I'm not very up to date on how MutationObserver works.

Why wouldn't our original solution just work?

**Comment by anoblet** [comment]
`opened-changed` only fires once when the top level menu is opened. The submenu items have yet to be rendered, and aren't able to be modified.

This use case of `MutationObserver` is pretty efficient. Since it only fires on `firstUpdated` and only watches direct descendants of `document.body`, it should only fire on menu clicks.

**Comment by pawelkmpt** [comment]
@lkraav can we merge it?

**Comment by lkraav** [comment]
> @lkraav can we merge it?

I don't know, haven't been able to evaluate whether this is best available practice. Asking on Vaadin Discord would help convince.

**Comment by anoblet** [comment]
@lkraav https://discord.com/channels/732335336448852018/1064939525731790969/1064939525731790969

**Comment by pawelkmpt** [comment]
I see someone on Discord suggested different solution. Will you use it @anoblet ?

**Comment by anoblet** [comment]
@pawelkmpt I have updated the PR to use the technique from Vaadin Discord.

**Review by lkraav — APPROVED** [review]

**Pull request merged**
