### PR TITLE
Certificate header: credential fit

### PR DESCRIPTION
**Pull request by pawelkmpt**
Result after changes

Screenshot 2024-01-11 at 11 44 03
Screenshot 2024-01-11 at 11 44 18
Screenshot 2024-01-11 at 11 44 51
Screenshot 2024-01-11 at 11 45 11
Screenshot 2024-01-11 at 11 46 22
Screenshot 2024-01-11 at 11 46 35

### CODE REVIEW

**Comment by pawelkmpt** [comment]
Task linked: [CU-86ayg4prn Course complete page](https://app.clickup.com/t/86ayg4prn)

**Comment by heshfekry** [comment]
@pawelkmpt 

Certificate looks fine.

Unrelated to this but since its here too.

- Course title > H1
- Course completed > h2
- I noticed the same on MD 2,0 pages too. Title is a large lato instead of an H1.

**Comment by pawelkmpt** [comment]
> Certificate looks fine.
> 
> Unrelated to this but since its here too.
> 
> * Course title > H1
> * Course completed > h2
> * I noticed the same on MD 2,0 pages too. Title is a large lato instead of an H1.

@heshfekry  better?

Screenshot 2024-01-11 at 14 28 31

**Review by anoblet — APPROVED** [review]

**Comment by lkraav** [comment]
Sports psychology talks about avoiding negatives, like Don't stop, which puts the word Stop in athlete mind.

Better: «Keep going!»

**Pull request merged**
