### PR TITLE
build(cli deploy): bump storybook-deployer to 2.8.8

### PR DESCRIPTION
**Pull request by dominik-stypula-polcode**
Related to the latest fix in `storybook deployer`: https://github.com/storybookjs/storybook-deployer/pull/102

### CODE REVIEW

**Comment by lkraav** [comment]
1. This is `chore`, avoid inventing random. See https://github.com/commitizen/cz-cli

Commitize

2. Scope can only be something in `packages/`, or empty for global things. There is no "cli deploy" package. This is `chore(storybook)`

**Comment by dominik-stypula-polcode** [comment]
> 1. This is `chore`, avoid inventing random. See https://github.com/commitizen/cz-cli
> 
> Commitize

I actually use `Git Commit Template` plugin in PHPStorm for this, which has the following list of commit types, that is where the `build` type comes from

Screenshot from 2021-05-13 10-23-10

**Comment by lkraav** [comment]
> I actually use Git Commit Template plugin in PHPStorm for this, which has the following list of commit types, that is where the build type comes from

Repo makes the call of what gets in, IDE can't dictate it because not everybody commits in IDE.

I'm surprised commit linter allowed this message to pass, configuration is not as strong as it needs to be.

"Unknown" `build` type is the smaller issue than missing proper scope `storybook` package.

**Comment by lkraav** [comment]
Indeed `build` is listed in https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional README is interesting, taking a closer look.

**Review by lkraav — CHANGES_REQUESTED** [review]
Rebase on latest commitlint change, I think it should auto-check `packages/` scope, and auto-allow empty scope as well now :+1:

**Pull request merged**
