### PR TITLE
fix(Team Dashboard): conditional visibility of buttons

### PR DESCRIPTION
**Pull request by HenerHoop**
https://app.clickup.com/t/86ayqff97

### CODE REVIEW

**Comment by HenerHoop** [comment]
Task linked: [CU-86ayqff97 Manage team roadmaps display conditionally](https://app.clickup.com/t/86ayqff97)

**Comment by anoblet** [comment]
This looks good :)

We should get into the practice of using the `nothing` sentinel (https://lit.dev/docs/api/templates/#nothing) as opposed to returning an empty string in ternaries. This means `lit` throws away the template part for future evaluations, a small performance boost.

**Comment by HenerHoop** [comment]
> This looks good :)
> 
> We should get into the practice of using the `nothing` sentinel (https://lit.dev/docs/api/templates/#nothing) as opposed to returning an empty string in ternaries. This means `lit` throws away the template part for future evaluations, a small performance boost.

@anoblet Thanks for this information. I updated the code.

**Review by pawelkmpt — CHANGES_REQUESTED** [review]
@HenerHoop please follow commit messages standard we use. Look and git log and see how it's usually done.

```diff
- fix(Team Dashboard): conditional visibility of buttons
+ refactor(cxl-ui): conditional visibility of buttons in team components
```

I'm actually surprised linter let you pass "Team Dashboard" in scope 🤔

**Comment by HenerHoop** [comment]
> @HenerHoop please follow commit messages standard we use. Look and git log and see how it's usually done.
> 
> ```diff
> - fix(Team Dashboard): conditional visibility of buttons
> + refactor(cxl-ui): conditional visibility of buttons in team components
> ```
> 
> I'm actually surprised linter let you pass "Team Dashboard" in scope 🤔

@pawelkmpt But why is the logic of front (aybolit) and back-end(wpstarter) commits different? In one, you need to refer to a packet, and in the other, to a class/feature?

**Comment by pawelkmpt** [comment]
> @pawelkmpt But why is the logic of front (aybolit) and back-end(wpstarter) commits different? In one, you need to refer to a packet, and in the other, to a class/feature?

They were developed separately and commit standards were set at different moments in time. Aybolit is also a fork from 3rd party developer and we followed what was defined there.

Worth mentioning, WPS became monorepo in the beginning of this year. Previously all items from `packages` directory were separate repositories. The best maintained was `institute-plugin`.

**Review by pawelkmpt — APPROVED** [review]

**Comment by HenerHoop** [comment]
> They were developed separately and commit standards were set at different moments in time. Aybolit is also a fork from 3rd party developer and we followed what was defined there.
> 
> Worth mentioning, WPS became monorepo in the beginning of this year. Previously all items from `packages` directory were separate repositories. The best maintained was `institute-plugin`.

But could we standardize this logic?

**Comment by pawelkmpt** [comment]
> But could we standardize this logic?

It ain't easy to standarize everything, but indeed it could be more explicit.

https://app.clickup.com/2317190/v/dc/26pw6-8023/26pw6-7161

**Pull request merged**
