### PR TITLE
refactor(cxl-ui): rename 'cxl-like-or-dislike' to 'cxl-vote'

### PR DESCRIPTION
**Pull request by anoblet**
Closes:

- #174

### CODE REVIEW

**Review by pawelkmpt — APPROVED** [review]

**Comment by lkraav** [comment]
Shouldn't target branch be `playbooks`?

**Review by lkraav — APPROVED** [review]

**Comment by pawelkmpt** [comment]
> Shouldn't target branch be `playbooks`?

Indeed. I just changed it @lkraav and see conflicts. @anoblet can you take a look?

**Comment by anoblet** [comment]
Fixed

**Comment by lkraav** [comment]
Since `playbooks` got merged, I switched branch back to `master`.

**Comment by pawelkmpt** [comment]
We're not using it anymore.

**Pull request closed without merging**
