### PR TITLE
feat(cxl-lumo-styles): add badge

### PR DESCRIPTION
**Pull request by pawelkmpt**
https://vaadin.com/docs/latest/components/badge

Screenshot 2023-01-25 at 11 23 24

### CODE REVIEW

**Comment by lkraav** [comment]
Do we also have an idea of what our actual usage story could look like?

**Comment by pawelkmpt** [comment]
> Do we also have an idea of what our actual usage story could look like?

image

**Comment by pawelkmpt** [comment]
@lkraav ping

**Review by anoblet — APPROVED** [review]
LGTM

**Pull request merged**
