### PR TITLE
feat: add locked state to cards

### PR DESCRIPTION
**Pull request by anoblet**
https://app.clickup.com/t/86b1nztyh

Course card:

image

Light card:

image

### CODE REVIEW

**Comment by heshfekry** [comment]
Hey @anoblet 

Good start. What you showed here would be difficult for users as they can not see the title of the course, so they will just see a list of CTAs and the same microcopy. Original intention was to swap the excerpt.

What you showed however could work on hover. Something like this?

Normal state
image

On-hover state
image

**Comment by heshfekry** [comment]
@anoblet if you are struggling to get hover to work properly, then we can just try originally intended version.

**Review by pawelkmpt — COMMENTED** [review]
This is overcomplicated. Also such message should not be hardcoded. It was supposed to replace regular course description.

**Comment by lkraav** [comment]
"All-Access" product name always hyphenated, right?

Unsure: do we need to repeat CXL? I mean who else's All-Access are we selling?

**Comment by heshfekry** [comment]
> Unsure: do we need to repeat CXL? I mean who else's All-Access are 

BRAAAANDDDDDD!!!! 

I agree and am definitely up for removing repetition here, its redundant. Especially in a tooltip which is latest incarnation proposed by @pawelkmpt 

image

**Comment by pawelkmpt** [comment]
Screenshot 2024-08-14 at 12 06 50

**Comment by pawelkmpt** [comment]
> Also such message should not be hardcoded.

Made it hardcoded as @heshfekry suggested message different than we currently use but provided override possibility.

**Comment by pawelkmpt** [comment]
`cxl-light-card` locked

Screenshot 2024-08-14 at 14 33 03

**Pull request merged**
