### PR TITLE
feat(cxl-ui): add institute page filtering components

### PR DESCRIPTION
**Pull request by freudFlintstone**
Task: https://app.clickup.com/t/861mzgnx5

Dependencies: https://github.com/conversionxl/aybolit/pull/293

### CODE REVIEW

**Comment by freudFlintstone** [comment]
These changes depend on being able to replace some of the elements rendered by the FacetWP plugin. Here's a gist for a similar problem:
https://gist.github.com/MWDelaney/7f3ff797041bac5ef9918112d6a43816

**Comment by pawelkmpt** [comment]
@freudFlintstone start over and created new branch from `feat/dashboard` not `master`. Otherwise we'll get into bunch of conflicts.

**Comment by freudFlintstone** [comment]
But it was branched from `feat/dashboard`: https://github.com/conversionxl/aybolit/network
Maybe the problem is that I rebased my local feat/dashboard on master, like we talked about [here](https://github.com/conversionxl/aybolit/pull/293#issuecomment-1630720011)
I'll just pull `feat/dashboard` again and reapply these changes

Screenshot from 2023-07-14 08-01-17

**Comment by pawelkmpt** [comment]
> Maybe the problem is that I rebased my local feat/dashboard on master, like we talked about [here](https://github.com/conversionxl/aybolit/pull/293#issuecomment-1630720011) I'll just pull `feat/dashboard` again and reapply these changes

It should've been pushed then. I've tried that ITMW but noticed other PRs which started from `feat/dashboard` get conflicts.

**Comment by freudFlintstone** [comment]
I tried pushing and had an issue too. The cards PR has a similar problem. Should I fix feat/dashboard and everyone can rebase after, or just start this one over?

**Comment by pawelkmpt** [comment]
> I tried pushing and had an issue too. The cards PR has a similar problem. Should I fix feat/dashboard and everyone can rebase after, or just start this one over?

Just start this one over. I'll rebase `feat/dashboard` later. `master` doesn't have any critical updates needed for dashboard work

**Pull request closed without merging**
