### PR TITLE
feat(cxl-ui): wip adjust dropdown menu positioning

### PR DESCRIPTION
**Pull request by saas786**
cu-task: https://app.clickup.com/t/28fubth

### CODE REVIEW

**Comment by anoblet** [comment]
Alignment on the y-axis works. Alignment on the x-axis doesn't seem to correspond with the menu items (this might be a screen size issue.) There's also a UX glitch where when you un-focus the menu item (such as by trying to click a different menu item), you see a flash of different frames, and the second click doesn't register.

https://www.loom.com/share/d78216e1c643419280dcf9e66b4fa37a

community.cxl.com uses `vaadin-menu-bar` as opposed to `vaadin-tabs`. `vaadin-menu-bar` handles positioning, responsiveness etc. out of the box. It would take some work, though it might make sense to consider using `vaadin-menu-bar` instead.

**Comment by saas786** [comment]
> community.cxl.com

Issues you mentioned are replicable on live https://cxl.com/institute/

Target of this PR is to verify if dropdown (top) menu appears just below the clicked menu, and cantered under the clicked menu.
You can also experiment with the code and improve it as you see fit.

`vaadin-menu-bar` what benefits you saw over vaadin-tabs?

**Comment by anoblet** [comment]
The double click needed to switch menu items happens on live. I don't see the flash of frames though.

`cxl-menu-bar` was meant for this use case, and doesn't need any additional logic position, changing of screen sizes etc.

**Comment by lkraav** [comment]
I recommended to close this PR https://app.clickup.com/t/28fubth?comment=1099495929

**Comment by saas786** [comment]
> I recommended to close this PR [app.clickup.com/t/28fubth?comment=1099495929](https://app.clickup.com/t/28fubth?comment=1099495929)

Closing as suggested.

**Comment by lkraav** [comment]
> Closing as suggested.

I would've waited for @heshfekry to get back and also comment.

**Pull request closed without merging**
