### PR TITLE
visual regression testing

### PR DESCRIPTION
**Pull request by anoblet**

### CODE REVIEW

**Comment by lkraav** [comment]
Nice!

Looking at example `screenshots/Chrome/baseline/cxl-card.png` is it missing the face thumbnail, or?

**Comment by anoblet** [comment]
I see that, here are the two outstanding issues:

1) Thumbnail is missing from cloud run versions of WTR
2) Lumo styles are not applied (local/cloud)

Loading `@vaadin/vaadin-lumo-styles/all-imports` in either the story or the test imports  `--lumo-*` properties, but `--cxl-*` properties are still missing.

I'm going to check in the Lit Slack to see if anybody knows anything about the thumbnail issue. The issue with the styles not loading I might have to tinker around with.

**Comment by anoblet** [comment]
I got the thumbnail working, and importing `@vaadin/vaadin-lumo-styles` in the test seems to visually make everything seem correct. @lkraav Could you verify by pulling down this PR, running `yarn test:web-test-runner --manual` and inspecting the styles?

Here's a link showing the update: https://github.com/conversionxl/aybolit/commit/e1b44f7c28f2a5f5924edd37525a696e92e9fe1a

**Comment by pawelkmpt** [comment]
@anoblet 1,5 year later - does it have potential to use or technology and circumstances have changed since then?

**Comment by anoblet** [comment]
https://github.com/conversionxl/aybolit/pull/202#issuecomment-1651114908 This PR might be more turnkey, though If we want to keep costs low, this solution would work.

**Pull request closed without merging**
