### PR TITLE
CXL Search

### PR DESCRIPTION
**Pull request by dominik-stypula-polcode**
https://github.com/conversionxl/cxl-playbook-blocks/issues/85
video: https://www.loom.com/share/f015e392e4d54d9d86a4aca6e188e87a
Deploy: https://cxl-search-deploy.netlify.app/?path=/story/cxl-search--cxl-search

### CODE REVIEW

**Comment by lkraav** [comment]
Can you also Netlify this @dominik-stypula-polcode

**Comment by dominik-stypula-polcode** [comment]
> Can you also Netlify this @dominik-stypula-polcode
> 
>  any other bigger PRs that could benefit

https://cxl-search-deploy.netlify.app/?path=/story/cxl-search--cxl-search

**Comment by pawelkmpt** [comment]
What's the status of it @dominik-stypula-polcode @lkraav @heshfekry ?

**Comment by heshfekry** [comment]
@pawelkmpt This is on hold, I believe when we get to the text-based search result the idea was to fish relevant pieces from here.

**Comment by pawelkmpt** [comment]
Obsolete

**Pull request closed without merging**
