### PR TITLE
Playbooks main PR v2

### PR DESCRIPTION
**Pull request by lkraav**
Replaces #93

### CODE REVIEW

**Comment by pawelkmpt** [comment]
@lkraav is it likely you'll have a chance to give us green light anytime soon?

**Comment by lkraav** [comment]
> @lkraav is it likely you'll have a chance to give us green light anytime soon?

Time allocation is not looking great just yet, but can you remind me what the planned steps here are?

**Comment by saas786** [comment]
> > @lkraav is it likely you'll have a chance to give us green light anytime soon?
> 
> Time allocation is not looking great just yet, but can you remind me what the planned steps here are?

`playbooks` branch is already in sync with `master` branch commits. So should be a simple merge?

`playbooks` -> `master` -> release

**Review by saas786 — APPROVED** [review]

**Comment by saas786** [comment]
@pawelkmpt can I close this?

As it seems like you have merged it into branch **playbooks**

**Comment by saas786** [comment]
> > @pawelkmpt can I close this?
> > As it seems like you have merged it into branch **playbooks**
> 
> I don't know. I have trouble understanding what is what in this repo. @lkraav some time ago mentioned about making `master` default again. Did it happen? If not, do you have enough knowledge to decide if `playbooks` can be merged into `master` or whatever merged into `master` and be stable?
> 
> I'm afraid @lkraav might not have enough time for such tasks, so the person which feels the most fluent in the repo should make decision. It's not me though.

Ideally `playbooks` branch should be easily merged into `master` branch, as you have kept `playbooks` in sync with `master`.

If some conflict occurs, I can try to resolve it.

You can do:

create two test branchs
- master -> master-test
- playbooks -> playbooks-test

and do a test merge from `playbooks-test` to `master-test` and see if it causes to many conflicts or not. If handful of conflicts or none, than you can just simply merge `playbooks` onto `master`.

And once merged, we can create `develop` rebased from `master` and remove `playbooks` to avoid future confusions.

Make sense?

**Comment by saas786** [comment]
Just noticed: https://github.com/conversionxl/aybolit/pull/179/conflicts

and not many conflicts, I can resolve the conflicts.

Primary conflict is: 
Loom_b8OveqqQIc

For that I will need to build icons base64 svg, that shouldn't be an issue.

I am going to resolve conflicts and will let you know, so you can merge it.

**Comment by kylebrodeur** [comment]
Task linked: [CU-2xgwjnj Aybolit playbooks -> master branch resolve PR conflicts](https://app.clickup.com/t/2xgwjnj)

**Review by pawelkmpt — APPROVED** [review]
I'm approving, @saas786 will test and then we'll do release.

**Pull request merged**
