### PR TITLE
utilize cxl-headroom LitElement component

### PR DESCRIPTION
**Pull request by saas786**
https://github.com/conversionxl/aybolit/issues/29
https://github.com/conversionxl/aybolit/pull/28
https://github.com/conversionxl/aybolit/issues/29

### CODE REVIEW

**Comment by lkraav** [comment]
We copied headroom source and now have to maintain it ourselves?

**Comment by lkraav** [comment]
We copied headroom scroll / business logic and now have to maintain it ourselves for all updates?

I am not sure I see myself importing hundreds of lines of foreign complex code into this repo. It's basically more sensible to just use headroom.js as an app-level library and configure it there, until upstream gets it together and makes an importable JS library. It would've made more sense to pay someone to work directly on upstream, instead of this copy-paste solution.

**Comment by saas786** [comment]
> We copied headroom scroll / business logic and now have to maintain it ourselves for all updates?
> 
> I am not sure I see myself importing hundreds of lines of foreign complex code into this repo. It's basically more sensible to just use headroom.js as an app-level library and configure it there, until upstream gets it together and makes an importable JS library. It would've made more sense to pay someone to work directly on upstream, instead of this copy-paste solution.

I am ok with either way.

We use Headroom.JS in themes directly.

or

We use this new implementation in web components.

As far as new implementation is concerned, I was think of separating it from "CXL UI" and instead host it as a standard along package just like other Headroom ports for Angular, Vue & React.

We can open it for community so we can utilize community support.

As far as I can see, there is no maintenance for our port, as long as LitElement doesn't change in near future.

Let me know your thoughts.

**Comment by lkraav** [comment]
> As far as I can see, there is no maintenance for our port, as long as LitElement doesn't change in near future.

How come just LitElement? If Headroom changes / improves any algorithm, you'd have to refactor this code as well, no?

**Comment by lkraav** [comment]
> As far as new implementation is concerned, I was think of separating it from "CXL UI" and instead host it as a standard along package just like other Headroom ports for Angular, Vue & React.

From what I see, all of these copy-paste Headroom's logic.

I posted https://github.com/WickyNilliams/headroom.js/issues/347#issuecomment-565433814 not sure if this has been asked before in some Headroom closed issue, but I wasn't able to find this being discussed in any other open issues.

Where and when did you ask the author how you would be able to avoid a full copy-paste of their logic code?

**Comment by saas786** [comment]
> How come just LitElement? If Headroom changes / improves any algorithm, you'd have to refactor this code as well, no?

No, our code is not dependent on original HeadroomJS instead its more similar to React Port of HeadroomJS, which hasn't changed logic wise in last year or so, only few bug fixes / tweaks. And we can easily sync it with React version without refactor etc.

Our code is almost same as React version, only difference is the component life cycle methods between React Component & LitElement Component.

**Comment by lkraav** [comment]
> No, our code is not dependent on original HeadroomJS instead its more similar to React Port of HeadroomJS, which hasn't changed logic wise in last year or so, only few bug fixes / tweaks. And we can easily sync it with React version without refactor etc.

Doesn't make it any better - it's still hundreds of lines of logic that belongs somewhere else. React port is sitting on top of the same problem.

**Comment by saas786** [comment]
What you suggest?

I explained the status of the code, it doesn't need much maintenance, and we can move it to separate repo so if we are not sure about it, we can just remove the dependency and that will be it.

We don't have to keep it in "cxl-ui" package in order to use it.

**Pull request closed without merging**
