### PR TITLE
feat: bring gravity forms styes and add gravity form story

### PR DESCRIPTION
**Pull request by anoblet**
This adds a gravity form story with an optional pending state.

### CODE REVIEW

**Comment by lkraav** [comment]
Story should be a support element for an actual implementation of something.

We're looking to get a central style asset that the story can use.

I think we want to model it to live at somewhere like https://github.com/conversionxl/aybolit/tree/master/packages/cxl-lumo-styles/scss/gravityforms.scss?

**Comment by anoblet** [comment]
@saas786 Is there anything else we should be adding?

**Comment by kylebrodeur** [comment]
Task linked: [CU-2c1y7zk Migrate GForm styles from `wp-theme-lib` to aybolit](https://app.clickup.com/t/2c1y7zk)

**Comment by saas786** [comment]
@anoblet please create a separate PR for https://app.clickup.com/t/232pth1

Keep current PR open just move this code:

https://github.com/conversionxl/aybolit/blob/373ad669f802fb07e1f6a1acd7dce9153e3c5dec/packages/cxl-lumo-styles/scss/gravity-forms.scss#L23

to new PR.

**Comment by lkraav** [comment]
It's OK to hold off on this until I have some time to look into details.

**Comment by pawelkmpt** [comment]
@anoblet should Gravity Form tab on the left show anything? It's blank screen for me

**Comment by saas786** [comment]
> @anoblet should Gravity Form tab on the left show anything? It's blank screen for me

@anoblet somehow it still shows [unresolved]

chrome_N3EkyXhjhS

**Comment by anoblet** [comment]
@pawelkmpt @saas786 

It seems to be coming from this line: https://github.com/conversionxl/aybolit/blob/f88d7a396f66549c92115a531480e6a7a497ca82/packages/cxl-lumo-styles/scss/loading.css#L46-L49

I need to take a look at why `[unresolved]` is still targeted.

**Comment by anoblet** [comment]
I'm not sure we should be loading `loading.css` here: https://github.com/conversionxl/aybolit/pull/200/commits/30e8c993eebc1151a70faf0e19d1b31aa67d6b6b

**Comment by pawelkmpt** [comment]
Should it have spinner?

Screenshot 2022-10-21 at 15 34 17

**Comment by anoblet** [comment]
@pawelkmpt 

I was asked to separate the spinner into a separate PR: https://github.com/conversionxl/aybolit/pull/200#issuecomment-1127526597

Here is the PR for the spinner: https://github.com/conversionxl/aybolit/pull/226

**Comment by pawelkmpt** [comment]
> I was asked to separate the spinner into a separate PR: [#200 (comment)](https://github.com/conversionxl/aybolit/pull/200#issuecomment-1127526597)

Weird but OK.

> Here is the PR for the spinner: #226

It does not load, similar to what we had here.

**Comment by saas786** [comment]
> > Here is the PR for the spinner: #226
> 
> It does not load, similar to what we had here.

@anoblet 

It should in #226, separation doesn't mean it should not work.

**Comment by anoblet** [comment]
@pawelkmpt @saas786 

#226 Had the same `loading.css` import. I removed it.

**Review by pawelkmpt — CHANGES_REQUESTED** [review]
@anoblet please squash f88d7a396f66549c92115a531480e6a7a497ca82 & 30e8c993eebc1151a70faf0e19d1b31aa67d6b6b

**Comment by pawelkmpt** [comment]
Once done I can make a release together with already merged #230

**Comment by anoblet** [comment]
@pawelkmpt Squashed

**Review by pawelkmpt — APPROVED** [review]

**Pull request merged**
