### PR TITLE
feat(cxl-lumo-styles): increase default font size

### PR DESCRIPTION
**Pull request by anoblet**
https://cxlworld.slack.com/archives/C01JABH8AHX/p1720530653218939

### CODE REVIEW

**Comment by pawelkmpt** [comment]
Everything looks huge and unnatural with this change: https://deploy-preview-422--conversionxl-aybolit.netlify.app/?path=/story/cxl-ui-cxl-app-layout--cxl-app-layout-2-cr

Original: https://conversionxl.github.io/aybolit/?path=/story/cxl-ui-cxl-app-layout--cxl-app-layout-2-cr

I don't think we should edit it right now.

**Comment by lkraav** [comment]
> Everything looks huge and unnatural

Overuse of hyperboles? Definitely worth a look @heshfekry. Yes, after resetting the base, maybe some individual elements might need adjustment, but overall everything flows into better visibility state quite well.

**Comment by heshfekry** [comment]
@lkraav Impossible to say definitively without comparison images. 

Can we organize that somehow @pawelkmpt ?

I am net getting a this is completely off the cards vibe though. More of some things just need a tweak.

**Comment by pawelkmpt** [comment]
> @lkraav Impossible to say definitively without comparison images.
> 
> Can we organize that somehow @pawelkmpt ?

I made screenshots but they didn't reflect the difference. Therefore I pasted these links. If you open them in two different tabs you'll spot the difference. It's clearly visible.

> I am net getting a this is completely off the cards vibe though. More of some things just need a tweak.

I think we have enough important tasks to work on, no need to focus on global font change now.

**Comment by heshfekry** [comment]
Ah i did not notice 2 links.

> I think we have enough important tasks to work on, no need to focus on global font change now.

Discussing on an improvement isn't always a drop everything and do it call to action. [This type of task lives in the low hanging fruit task](https://app.clickup.com/t/86azbhf59)

We are deciding now whether it is worth pursuing or not. We can prioritise later.

------------

Based on what i see i think the biggest upgrade is still long form p text. Increasing only the p font could be enough for now. 

Everything else needs to much work and testing if we are to treat this as a quick upgrade. Things like space in menu items and action bar etc. Things could break across the board if this is a true global change.

## Large

image

## Small

image

**Comment by anoblet** [comment]
I didn't realize you can't reopen a PR after you've force pushed. Here is the new PR: https://github.com/conversionxl/aybolit/pull/423

**Pull request closed without merging**
