### PR TITLE
refactor(cxl-ui): cxl-course-card, dashboard

### PR DESCRIPTION
**Pull request by pawelkmpt**
* remove new (star) icon
* make tag more prominent, styled as one from cxl-light-card

https://app.clickup.com/t/86az50h3y?comment=90140017966111

BEFORE
Screenshot 2024-01-25 at 08 00 12

AFTER
Screenshot 2024-01-25 at 07 59 35

### CODE REVIEW

**Comment by pawelkmpt** [comment]
Task linked: [CU-86az50h3y Dashboard - MD 2.0 - Institute optimization](https://app.clickup.com/t/86az50h3y)

**Review by anoblet — APPROVED** [review]

**Comment by anoblet** [comment]
We might be able to use `badge` from Vaadin in the future: https://vaadin.com/docs/latest/components/badge

**Comment by anoblet** [comment]
Since the height of the pill is larger than the tags, I would suggest vertically aligning everything.

```
.tags {
  align-items: center;
}
```

**Comment by pawelkmpt** [comment]
> Since the height of the pill is larger than the tags, I would suggest vertically aligning everything.
> 
> https://github.com/conversionxl/aybolit/blob/84b86e3227a42b34859a1cd2c439350cad16b45b/packages/cxl-ui/scss/cxl-base-card.scss#L118
> 
> ```
> .tags {
>   align-items: center;
> }
> ```

Done @anoblet  :)

**Pull request merged**
