### PR TITLE
fix(cxl-ui): fix mobile layout issues in course pages

### PR DESCRIPTION
**Pull request by freudFlintstone**

### CODE REVIEW

**Comment by freudFlintstone** [comment]
Task linked: [CU-86aykudx5 Deployment of new component](https://app.clickup.com/t/86aykudx5)

**Comment by anoblet** [comment]
This looks good! It seems you have a better idea of the issue and could have it solved quicker. Should we revert this commit? https://github.com/conversionxl/aybolit/commit/73a306b4358fb4b5bf6922a826c0a4a22f24c3c8

**Comment by freudFlintstone** [comment]
> This looks good! It seems you have a better idea of the issue and could have it solved quicker. Should we revert this commit? [73a306b](https://github.com/conversionxl/aybolit/commit/73a306b4358fb4b5bf6922a826c0a4a22f24c3c8)

@anoblet I definitely wish I had understood the issue faster. But this is not a proper fix, it's just workaround, since we still don't know what's causing the overflow.

Do not revert the other commit. It fixes a real issue that would have the same effect. The reason I thought it was the only  cause is that it fixed it in local development.

**Review by anoblet — APPROVED** [review]
This should fix the menu gap issue. Adding overflow hidden to cxl-app-layout works using inspector on live. There's also a chance it could fix some of the animation issues we face when opening the menu for the first time.

**Comment by pawelkmpt** [comment]
@anoblet I tested the code on live, fixed one issue @freudFlintstone introduced (missing card styles due the removal of `@import` clause).

I also deleted b5a9f3893cd75f89778092d148ff316f656336e3 with `overflow: hidden` for `cxl-app-layout` as it's just hiding an issue, not solving it and also can cause problems in other places.

This code is live on blog and institute.

**Comment by anoblet** [comment]
This seems to fix https://cxl.com/webinars. On Institute pages we still have a horizontal scroll which I can't seem to find in inspector.

**Review by pawelkmpt — APPROVED** [review]

**Pull request merged**
