### PR TITLE
chore(cxl-ui): upgrade lit-html to 2.0.0-rc.3

### PR DESCRIPTION
**Pull request by anoblet**

### CODE REVIEW

**Comment by lkraav** [comment]
Missing lock file update, or?

**Comment by anoblet** [comment]
Not sure. The PR built fine without the lit-html upgrade. Once merged got complaints about missing lit-html dependencies.

**Comment by anoblet** [comment]
This builds fine. I gave it to @dominik-stypula-polcode to test.

**Comment by lkraav** [comment]
> This builds fine. I gave it to @dominik-stypula-polcode to test.

Indeed, it builds now, but what's the magic behind this change - we are changing lit-html major version, but lockfile doesn't change at all.

Is this some transition helper thing Lit team provisions, or?

**Comment by anoblet** [comment]
The new lit-html version includes the backward dependency utilities. I believe this is required by the new Storybook. Not sure why the build didn't complain in the previous PR.

**Pull request closed without merging**
