### PR TITLE
remove obsolete @cwmr/iron-star-rating dependency

### PR DESCRIPTION
**Pull request by anoblet**
https://github.com/conversionxl/aybolit/pull/237#issuecomment-1330448020

### CODE REVIEW

**Comment by saas786** [comment]
@anoblet 

`yarn.lock` missing.

**Comment by anoblet** [comment]
@saas786 Fixed

**Comment by saas786** [comment]
> @saas786 Fixed

Incorrect `yarn.lock` file, should be like this: [yarn.lock](https://github.com/conversionxl/aybolit/commit/6640863#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de)

Yours have other changes to, should only contain removal changes.

**Comment by anoblet** [comment]
I usually remove `yarn.lock` and run `yarn install`. I guess this doesn't give us the best picture for package versions. I re-ran without removing `yarn.lock`.

**Review by saas786 — APPROVED** [review]
Looks good.

**Comment by saas786** [comment]
> I usually remove `yarn.lock` and run `yarn install`. I guess this doesn't give us the best picture for package versions. I re-ran without removing `yarn.lock`.

:) yeah, if we are maintaining it via GH, need to do it on existing `yarn.lock`, creating new changes it a whole lot, bring updated packages and what not.

**Comment by lkraav** [comment]
Completed in #237

**Pull request closed without merging**
