### PR TITLE
fix(cxl-ui): add dashboard accordion new styles

### PR DESCRIPTION
**Pull request by kertuilves**
https://app.clickup.com/t/86ay6gc3z

### CODE REVIEW

**Comment by pawelkmpt** [comment]
Design doesn't have indents on every level

Screenshot 2023-09-06 at 14 40 37

**Comment by kertuilves** [comment]
@heshfekry @pawelkmpt When I saw that the design that was under task description was missing from Figma I asked Janeli about it. She said that @heshfekry picked after our meeting this new design. Is this correct information?

Screenshot 2023-09-06 at 15 45 46

**Comment by heshfekry** [comment]
> @heshfekry @pawelkmpt When I saw that the design that was under task description was missing from Figma I asked Janeli about it. She said that @heshfekry picked after our meeting this new design. Is this correct information?
> 
> Screenshot 2023-09-06 at 15 45 46

Yes this is the same one, maybe it was moved. Basically the same with a slightly larger indent on left hand side.

**Review by pawelkmpt — CHANGES_REQUESTED** [review]
@heshfekry I think we need to skip indents on mobile as full card is not displayed

Screenshot 2023-09-07 at 15 07 49
Screenshot 2023-09-07 at 15 07 57
Screenshot 2023-09-07 at 15 08 03

**Comment by freudFlintstone** [comment]
> @heshfekry I think we need to skip indents on mobile as full card is not displayed
> 
Made that change for smaller screens, but I have a question: If cards are only ever rendered in lower level, does indenting actually contribute, or at least contributes enough that it's worth losing that space on larger mobile devices and tablets?

**Comment by heshfekry** [comment]
We need to ditch indent on mobile.

**Review by pawelkmpt — APPROVED** [review]

**Pull request merged**
