### PR TITLE
feat(cxl-ui): migrate to lit

### PR DESCRIPTION
**Pull request by anoblet**

### CODE REVIEW

**Comment by anoblet** [comment]
* Formatting happens automatically on commit.
* Unable to migrate `cxl-lumo-styles`  check as styles are generated using `css` from `@vaadin/vaadin-themable-mixin/register-styles.js` and an `instanceOf` check errors.

https://github.com/conversionxl/aybolit/blob/3a168e3bdf8df01c45af8b3c74dfd704a4cb64ab/packages/cxl-lumo-styles/src/utils.js#L2
https://github.com/conversionxl/aybolit/blob/3a168e3bdf8df01c45af8b3c74dfd704a4cb64ab/packages/cxl-lumo-styles/src/utils.js#L17
https://github.com/conversionxl/aybolit/blob/3a168e3bdf8df01c45af8b3c74dfd704a4cb64ab/packages/sass-render/sass-template.tmpl#L1

**Comment by lkraav** [comment]
What are your thoughts on https://twitter.com/serhiikulykov/status/1392156377838145536 @anoblet

**Comment by anoblet** [comment]
> What are your thoughts on https://twitter.com/serhiikulykov/status/1392156377838145536 @anoblet
> 
> https://github.com/web-padawan/lit-vaadin-helpers/blob/master/src/demo/context-menu-renderer-demo.ts 🤔

@lkraav That looks pretty awesome. Upgrade Vaadin components will be it's own beast I feel.

**Comment by lkraav** [comment]
#184 or later takes over.

**Pull request closed without merging**
