### PR TITLE
chore(cxl-ui): yarn upgrade-interactive --latest --scope '@vaadin'

### PR DESCRIPTION
**Pull request by anoblet**
https://github.com/anoblet/aybolit/pull/31

### CODE REVIEW

**Comment by lkraav** [comment]
I think we could attempt straight to latest v23.1 RC here from https://github.com/vaadin/web-components/releases

Currently https://github.com/vaadin/web-components/releases/tag/v23.1.0-rc3

**Comment by lkraav** [comment]
After `yarn upgrade-interactive` struggled with 

I manually upgraded all packages, WP at https://github.com/web-padawan/aybolit/compare/conversionxl:master...conversionxl:leho-vaadin-upgrade?expand=1

Next step: build test for Storybook, there's no way it's going to just work, knowing some of the refactors Vaadin has done.

**Comment by anoblet** [comment]
I ran into https://github.com/yarnpkg/yarn/issues/7734 as well. Deleting `yarn.lock` and running the command again allowed it to work.

I'll check out your branch and see what is left to be done.

**Comment by saas786** [comment]
> I think we could attempt straight to latest v23.1 RC here from [vaadin/web-components/releases](https://github.com/vaadin/web-components/releases)
> 
> Currently [vaadin/web-components@`v23.1.0-rc3` (release)](https://github.com/vaadin/web-components/releases/tag/v23.1.0-rc3)

Stable version is released: https://github.com/vaadin/web-components/releases/tag/v23.1.0

**Comment by saas786** [comment]
@anoblet closing, because of: https://github.com/conversionxl/aybolit/commit/503f19b844ad475abfc75be688d69e3c68c4ae65

**Pull request closed without merging**
